services:
  n8n:
    image: docker.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=${PIPELINE_URL}
    volumes:
      - ./n8n_data:/home/node/.n8n
    env_file:
      - .env
  
  speech_recognition:
    container_name: speech_recognition
    build: ./speech_recognition
    ports:
      - 8001:8001
    depends_on:
      - n8n
  
  restapi:
    container_name: restapi
    build: ./djangoapp
    ports:
      - 8000:8000
    depends_on:
      - n8n
      - speech_recognition
      - postgres
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
      - DEBUG=true
    command: >
      sh -c "./wait-for-it.sh postgres:5432 -- 
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - conversify_postgres:/var/lib/postgresql/data

volumes:
  conversify_postgres:
