# Generated by Django 5.2.6 on 2025-09-27 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Documents')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 9, 27, 15, 25, 8, 701117))),
            ],
        ),
    ]
